[package]
name = "cryptopals"
version = "0.0.0"
authors = ["Mack Stump <mack@mackstump.com>"]
edition = "2024"

[dependencies]
base64 = "0.22.1"
console = "0.16.0"
indicatif = "0.18.0"
rand = "0.9.1"
rayon = "1.10.0"

crypto = { path = "crypto" }

[workspace]
members = ["crypto"]
